name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Build & (option) tests Spring Boot ----------
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Spring Boot (skip tests if none)
        run: |
          cd springboot-app
          chmod +x mvnw || true
          ./mvnw -q -DskipTests package || mvn -q -DskipTests package

      # ---------- Tests Flask (pytest) ----------
      - name: Python deps for Flask tests
        run: |
          python -m pip install --upgrade pip
          pip install -r flask-app/requirements.txt
          pip install pytest

      - name: Run Flask unit tests
        run: |
          cd flask-app
          pytest -v

      # ---------- Docker login (uses repo secrets) ----------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------- Build & push images ----------
      - name: Set image tags
        id: meta
        run: |
          echo "SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "LATEST=latest" >> $GITHUB_OUTPUT

      - name: Build & push Spring Boot image
        run: |
          docker build -t kanisira/springboot-app:${{ steps.meta.outputs.SHA }} ./springboot-app
          docker tag  kanisira/springboot-app:${{ steps.meta.outputs.SHA }} kanisira/springboot-app:${{ steps.meta.outputs.LATEST }}
          docker push kanisira/springboot-app:${{ steps.meta.outputs.SHA }}
          docker push kanisira/springboot-app:${{ steps.meta.outputs.LATEST }}

      - name: Build & push Flask image
        run: |
          docker build -t kanisira/flask-app:${{ steps.meta.outputs.SHA }} ./flask-app
          docker tag  kanisira/flask-app:${{ steps.meta.outputs.SHA }} kanisira/flask-app:${{ steps.meta.outputs.LATEST }}
          docker push kanisira/flask-app:${{ steps.meta.outputs.SHA }}
          docker push kanisira/flask-app:${{ steps.meta.outputs.LATEST }}
